# docker compose file to coordinate execution of all containers aided by  https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xix-deployment-on-docker-containers and chatGPT

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis-stack
    volumes:
      - icst_upload:/uploads
    restart: always
    
  redis-stack:
    image: "redis/redis-stack:latest"
    restart: always

  mysql:
    image: mysql:latest
    environment:
      DB_HOST: mysql
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: icst
      MYSQL_USER: jordan
      MYSQL_PASSWORD: icst
    ports:
      - "3308:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./../other/installation_scripts/database_setup.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  
  celery_worker:
    build: .
    depends_on:
      - mysql
      - redis-stack
    volumes:
      - icst_upload:/uploads
    entrypoint: [""]
    command:
      celery -A celery_worker.celery worker --pool=threads --loglevel=INFO
    restart: always


volumes:
  mysql:
  icst_upload: